Repository Tiketeer/Tiketeer-BE, pull requests merged in 2024-03, with the labels that each got.

#2 [DEV-6] Github Action CI 워크플로우 작성
  .github/workflows/pr-check.yml
  build.gradle
Labels: enhancement

#3 BE 서버 내 Swagger 설정
  README.md
  build.gradle
  src/main/java/com/tiketeer/Tiketeer/configuration/SwaggerConfig.java
Labels: documentation, enhancement

#6 [DEV-47] Ticket & Purchase & Ticketing 엔티티 작성
  src/main/java/com/tiketeer/Tiketeer/domain/member/Member.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/repository/MemberRepository.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/repository/OptRepository.java
  src/main/java/com/tiketeer/Tiketeer/domain/purchase/Purchase.java
  src/main/java/com/tiketeer/Tiketeer/domain/purchase/repository/PurchaseRepository.java
  src/main/java/com/tiketeer/Tiketeer/domain/role/Role.java
  src/main/java/com/tiketeer/Tiketeer/domain/role/RolePermission.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticket/Ticket.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticket/repository/TicketRepository.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/Ticketing.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/repository/TicketingRepository.java
Labels: enhancement

#8 [DEV-56] mysql docker compose file 추가
  .gitignore
  docker-compose.dev.yml
  src/main/resources/application.properties
Labels: enhancement

#11 [DEV-87] GlobalExceptionHandler 테스트 코드 작성
  src/main/java/com/tiketeer/Tiketeer/domain/member/exception/DuplicatedEmailException.java
  src/main/java/com/tiketeer/Tiketeer/exception/GlobalExceptionHandler.java
  src/test/java/com/tiketeer/Tiketeer/configuration/GlobalExceptionHandlerTestConfig.java
  src/test/java/com/tiketeer/Tiketeer/exception/DummyRestController.java
  src/test/java/com/tiketeer/Tiketeer/exception/GlobalExceptionHandlerTest.java
Labels: enhancement

#12 [DEV-88] 컨트롤러 레이어에서 공통으로 활용하기 위한 ApiResponse 작성
  src/main/java/com/tiketeer/Tiketeer/response/ApiResponse.java
  src/test/java/com/tiketeer/Tiketeer/configuration/SecurityDisableForTestConfig.java
  src/test/java/com/tiketeer/Tiketeer/exception/GlobalExceptionHandlerTest.java
Labels: enhancement

#13 [DEV-61] SecurityConfig & JwtService 구현
  build.gradle
  src/main/java/com/tiketeer/Tiketeer/auth/jwt/JwtPayload.java
  src/main/java/com/tiketeer/Tiketeer/auth/jwt/JwtService.java
  src/main/java/com/tiketeer/Tiketeer/configuration/SecurityConfig.java
  src/test/java/com/tiketeer/Tiketeer/auth/jwt/JwtServiceTest.java
  src/test/java/com/tiketeer/Tiketeer/configuration/SecurityDisableForTestConfig.java
  src/test/java/com/tiketeer/Tiketeer/exception/GlobalExceptionHandlerTest.java
  src/test/resources/application.yml
Labels: enhancement

#14 [DEV-59] Ticketing 생성 EP 구현
  src/main/java/com/tiketeer/Tiketeer/domain/member/repository/MemberRepository.java
  src/main/java/com/tiketeer/Tiketeer/domain/role/repository/RoleRepository.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticket/repository/TicketRepository.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/controller/TicketingController.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/dto/CreateTicketingCommand.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/dto/CreateTicketingResult.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/dto/PostTicketingRequest.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/dto/PostTicketingResponse.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/exception/EventTimeNotValidException.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/exception/SaleDurationNotValidException.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/service/TicketingService.java
  src/main/java/com/tiketeer/Tiketeer/exception/GlobalExceptionHandler.java
  src/main/java/com/tiketeer/Tiketeer/exception/code/TicketingExceptionCode.java
  src/main/java/com/tiketeer/Tiketeer/response/ApiResponse.java
  src/test/java/com/tiketeer/Tiketeer/domain/ticketing/service/TicketingServiceTest.java
Labels: enhancement

#15 [DEV-62] 이메일 인증 EP 작성
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/AuthController.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/dto/SetPasswordWithOtpRequestDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/exception/InvalidOtpException.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/service/MemberService.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/service/dto/InitMemberPasswordWithOtpCommandDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/controller/TicketingController.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/controller/dto/PostTicketingRequestDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/controller/dto/PostTicketingResponseDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/dto/PostTicketingResponse.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/service/TicketingService.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/service/dto/CreateTicketingCommandDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/service/dto/CreateTicketingResultDto.java
  src/main/java/com/tiketeer/Tiketeer/exception/GlobalExceptionHandler.java
  src/main/java/com/tiketeer/Tiketeer/exception/code/MemberExceptionCode.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/service/MemberServiceTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/ticketing/service/TicketingServiceTest.java
Labels: enhancement

#16 [DEV-64] member register controller, service, test 작성
  src/main/java/com/tiketeer/Tiketeer/domain/member/Member.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/MemberController.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/dto/MemberRegisterRequestDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/dto/MemberRegisterResponseDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/repository/OtpRepository.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/service/MemberRegisterService.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/service/dto/MemberRegisterCommandDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/service/dto/MemberRegisterResultDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/role/exception/RoleNotFoundException.java
  src/main/java/com/tiketeer/Tiketeer/exception/GlobalExceptionHandler.java
  src/main/java/com/tiketeer/Tiketeer/exception/code/RoleExceptionCode.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/repository/MemberRepositoryTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/repository/OtpRepositoryTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/service/MemberRegisterServiceTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/role/repository/RoleRepositoryTest.java
Labels: enhancement

#18 [DEV-90] JWT Auth filter 작성
  README.md
  src/main/java/com/tiketeer/Tiketeer/auth/FilterExceptionResolver.java
  src/main/java/com/tiketeer/Tiketeer/auth/JwtFilterExceptionResolver.java
  src/main/java/com/tiketeer/Tiketeer/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/tiketeer/Tiketeer/auth/jwt/JwtMetadata.java
  src/main/java/com/tiketeer/Tiketeer/configuration/SecurityConfig.java
  src/test/java/com/tiketeer/Tiketeer/auth/JwtFilterExceptionResolverTest.java
  src/test/java/com/tiketeer/Tiketeer/exception/GlobalExceptionHandlerTest.java
Labels: enhancement

#19 [DEV-79] email service 개발
  README.md
  build.gradle
  src/main/java/com/tiketeer/Tiketeer/configuration/EmailConfig.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/Otp.java
  src/main/java/com/tiketeer/Tiketeer/exception/code/EmailExceptionCode.java
  src/main/java/com/tiketeer/Tiketeer/infra/alarm/email/DefaultMimeMessageHelperFactory.java
  src/main/java/com/tiketeer/Tiketeer/infra/alarm/email/EmailService.java
  src/main/java/com/tiketeer/Tiketeer/infra/alarm/email/MimeMessageHelperFactory.java
  src/main/java/com/tiketeer/Tiketeer/infra/alarm/email/exception/MessagingRuntimeException.java
  src/test/java/com/tiketeer/Tiketeer/configuration/EmailConfig.java
  src/test/java/com/tiketeer/Tiketeer/configuration/MockJavaMailSenderImpl.java
  src/test/java/com/tiketeer/Tiketeer/infra/alarm/email/EmailServiceTest.java
Labels: enhancement

#22 [DEV-93] Auth 필터가 예외경로도 막는 이슈를 수정
  docker-compose.dev.yml
  src/main/java/com/tiketeer/Tiketeer/auth/constant/JwtMetadata.java
  src/main/java/com/tiketeer/Tiketeer/auth/constant/PublicPaths.java
  src/main/java/com/tiketeer/Tiketeer/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/tiketeer/Tiketeer/auth/jwt/JwtMetadata.java
  src/main/java/com/tiketeer/Tiketeer/configuration/SecurityConfig.java
Labels: enhancement

#21 [DEV-70] 티케팅 삭제 EP 개발
  src/main/java/com/tiketeer/Tiketeer/domain/ticket/service/TicketService.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticket/service/dto/DropAllTicketsUnderSomeTicketingCommandDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/controller/TicketingController.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/exception/DeleteTicketingAfterSaleStartException.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/exception/ModifyForNotOwnedTicketingException.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/service/TicketingService.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/service/dto/DeleteTicketingCommandDto.java
  src/main/java/com/tiketeer/Tiketeer/exception/GlobalExceptionHandler.java
  src/main/java/com/tiketeer/Tiketeer/exception/code/TicketingExceptionCode.java
  src/test/java/com/tiketeer/Tiketeer/domain/ticket/service/TicketServiceTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/ticketing/service/TicketingServiceTest.java
Labels: enhancement

#23 [DEV-84] refresh token 재발급 EP
  src/main/java/com/tiketeer/Tiketeer/configuration/SecurityConfig.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/constant/CookieConfig.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/AuthController.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/exception/InvalidTokenException.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/service/MemberService.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/service/dto/RefreshAccessTokenCommandDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/service/dto/RefreshAccessTokenResultDto.java
  src/main/java/com/tiketeer/Tiketeer/exception/code/AuthExceptionCode.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/service/MemberServiceTest.java
Labels: enhancement

#24 [DEV-78] 포인트 충전 EP 개발
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/MemberController.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/dto/ChargePointRequestDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/dto/ChargePointResponseDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/exception/InvalidPointChargeRequestException.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/exception/MemberIdAndAuthNotMatchedException.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/service/MemberPointService.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/service/dto/ChargePointCommandDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/service/dto/ChargePointResultDto.java
  src/main/java/com/tiketeer/Tiketeer/exception/GlobalExceptionHandler.java
  src/main/java/com/tiketeer/Tiketeer/exception/code/MemberExceptionCode.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/service/MemberPointServiceTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/service/MemberRegisterServiceTest.java
  src/test/java/com/tiketeer/Tiketeer/testhelper/TestHelper.java
  src/test/java/com/tiketeer/Tiketeer/testhelper/TestHelperTest.java
Labels: enhancement

#25 [DEV-63] 로그인 구현
  src/main/java/com/tiketeer/Tiketeer/auth/constant/PublicPaths.java
  src/main/java/com/tiketeer/Tiketeer/configuration/SecurityConfig.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/AuthController.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/dto/LoginRequestDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/dto/LoginResponseDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/exception/InvalidLoginException.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/service/LoginService.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/service/dto/LoginCommandDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/service/dto/LoginResultDto.java
  src/main/java/com/tiketeer/Tiketeer/exception/GlobalExceptionHandler.java
  src/main/java/com/tiketeer/Tiketeer/exception/code/MemberExceptionCode.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/controller/AuthControllerTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/service/LoginServiceTest.java
  src/test/java/com/tiketeer/Tiketeer/testhelper/TestHelper.java
Labels: enhancement

#33 [DEV-97] TestHelper 내 편의 메서드 추가 및 기존 테스트 적용
  src/test/java/com/tiketeer/Tiketeer/domain/member/controller/AuthControllerTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/service/LoginServiceTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/service/MemberPointServiceTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/service/MemberServiceTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/purchase/service/PurchaseServiceTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/ticket/service/TicketServiceTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/ticketing/service/TicketingServiceTest.java
  src/test/java/com/tiketeer/Tiketeer/testhelper/TestHelper.java
  src/test/java/com/tiketeer/Tiketeer/testhelper/TestHelperTest.java
Labels: enhancement

#27 [DEV-92] member register service에 email 전송 적용
  .gitignore
  README.md
  src/main/java/com/tiketeer/Tiketeer/domain/member/service/MemberRegisterService.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/service/dto/CreateEmailViewCommandDto.java
  src/main/java/com/tiketeer/Tiketeer/infra/alarm/email/view/AuthenticateEmailViewFactory.java
  src/main/java/com/tiketeer/Tiketeer/infra/alarm/email/view/EmailViewFactory.java
  src/test/java/com/tiketeer/Tiketeer/domain/ticketing/service/TicketingServiceTest.java
  src/test/java/com/tiketeer/Tiketeer/infra/alarm/email/view/AuthenticateEmailViewFactoryTest.java
  src/test/resources/application.yml
Labels: enhancement

#36 [DEV-91] Security 인가 설정 추가
  src/main/java/com/tiketeer/Tiketeer/auth/constant/PublicPaths.java
  src/main/java/com/tiketeer/Tiketeer/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/tiketeer/Tiketeer/configuration/SecurityConfig.java
Labels: enhancement

#34 [DEV-77] 멤버 판매목록 조회 API 개발
  src/main/java/com/tiketeer/Tiketeer/configuration/SecurityConfig.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/MemberController.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/dto/GetMemberTicketingSalesResponseDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/service/MemberTicketingService.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/service/dto/GetMemberTicketingSalesCommandDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/service/dto/GetMemberTicketingSalesResultDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/Ticketing.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/repository/TicketingRepository.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/controller/AuthControllerTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/controller/MemberControllerTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/service/MemberTicketingServiceTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/ticketing/repository/TicketingRepositoryTest.java
Labels: enhancement

#38 [DEV-67] 비밀번호 변경 수행 EP 구현
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/MemberController.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/dto/ResetPasswordRequestDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/exception/InvalidNewPasswordException.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/ResetPasswordUseCase.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/dto/ResetPasswordCommandDto.java
  src/main/java/com/tiketeer/Tiketeer/exception/GlobalExceptionHandler.java
  src/main/java/com/tiketeer/Tiketeer/exception/code/MemberExceptionCode.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/controller/MemberControllerTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/usecase/ResetPasswordUseCaseTest.java
  src/test/java/com/tiketeer/Tiketeer/testhelper/TestHelper.java
Labels: enhancement

#41 [DEV-105] 백엔드 아키텍처 개편
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/AuthController.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/MemberController.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/dto/ChargePointRequestDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/dto/GetMemberPurchasesResponseDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/dto/GetMemberResponseDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/dto/GetMemberTicketingSalesResponseDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/dto/LoginRequestDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/dto/MemberRegisterResponseDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/service/LoginService.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/ChargeMemberPointUseCase.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/GetMemberPurchasesUseCase.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/GetMemberTicketingSalesUseCase.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/GetMemberUseCase.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/InitPasswordWithOtpUseCase.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/LoginUseCase.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/MemberRegisterUseCase.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/RefreshAccessTokenUseCase.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/dto/ChargePointCommandDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/dto/ChargePointResultDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/dto/GetMemberCommandDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/dto/GetMemberPurchasesCommandDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/dto/GetMemberPurchasesResultDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/dto/GetMemberResultDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/dto/GetMemberTicketingSalesCommandDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/dto/GetMemberTicketingSalesResultDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/dto/InitMemberPasswordWithOtpCommandDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/dto/LoginCommandDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/dto/LoginResultDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/dto/MemberRegisterCommandDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/dto/MemberRegisterResultDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/dto/RefreshAccessTokenCommandDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/dto/RefreshAccessTokenResultDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/purchase/controller/PurchaseController.java
  src/main/java/com/tiketeer/Tiketeer/domain/purchase/repository/PurchaseRepository.java
  src/main/java/com/tiketeer/Tiketeer/domain/purchase/service/PurchaseService.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticket/usecase/dto/CreateTicketCommandDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/controller/TicketingController.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/repository/TicketingRepository.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/usecase/GetAllTicketingsUseCase.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/usecase/GetTicketingUseCase.java
  src/main/java/com/tiketeer/Tiketeer/infra/alarm/email/view/AuthenticateEmailViewFactory.java
  src/main/java/com/tiketeer/Tiketeer/infra/alarm/email/view/dto/CreateEmailViewCommandDto.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/service/LoginUseCaseTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/service/MemberTicketingServiceTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/usecase/ChargeMemberPointUseCaseTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/usecase/GetMemberPurchasesUseCaseTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/usecase/GetMemberUseCaseTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/usecase/InitPasswordWithOtpUseCaseTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/usecase/MemberRegisterUseCaseTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/usecase/RefreshAccessTokenUseCaseTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/purchase/service/PurchaseServiceTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/ticketing/usecase/GetAllTicketingsUseCaseTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/ticketing/usecase/GetTicketingUseCaseTest.java
  src/test/java/com/tiketeer/Tiketeer/infra/alarm/email/view/AuthenticateEmailViewFactoryTest.java
  src/test/java/com/tiketeer/Tiketeer/testhelper/TestHelper.java
Labels: refactor

#29 [DEV-83] member, auth controller test
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/AuthController.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/dto/ChargePointRequestDto.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/controller/AuthControllerTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/controller/MemberControllerTest.java
Labels: enhancement

#44 [DEV-117] 컨트롤러 테스트 실제 객체테스트가 가능한 헬퍼메소드 추가
  src/main/java/com/tiketeer/Tiketeer/response/ApiResponse.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/controller/MemberControllerTest.java
  src/test/java/com/tiketeer/Tiketeer/testhelper/TestHelper.java
  src/test/java/com/tiketeer/Tiketeer/testhelper/TestHelperTest.java
Labels: enhancement

#45 [DEV-118] 프로젝트 경로 및 인가 관리 방식 개선 작업
  src/main/java/com/tiketeer/Tiketeer/auth/RequestMatcherHolder.java
  src/main/java/com/tiketeer/Tiketeer/auth/constant/PublicPaths.java
  src/main/java/com/tiketeer/Tiketeer/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/tiketeer/Tiketeer/configuration/SecurityConfig.java
  src/test/java/com/tiketeer/Tiketeer/auth/RequestMatcherHolderTest.java
Labels: enhancement

#48 [DEV-120] TestHelper.cleanDB 성능 개선을 위해 deleteAllInBatch 적용
  src/test/java/com/tiketeer/Tiketeer/testhelper/TestHelper.java
Labels: enhancement

#47 [DEV-119] email service 링크 수정
  README.md
  src/main/java/com/tiketeer/Tiketeer/infra/alarm/email/view/AuthenticateEmailViewFactory.java
  src/test/java/com/tiketeer/Tiketeer/infra/alarm/email/view/AuthenticateEmailViewFactoryTest.java
  src/test/resources/application.yml
Labels: bug

#50 [DEV-89] 비밀번호 변경 메일 요청 EP 작성
  src/main/java/com/tiketeer/Tiketeer/auth/SecurityContextHelper.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/Otp.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/controller/MemberController.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/MemberRegisterUseCase.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/SendPasswordChangeEmailUseCase.java
  src/main/java/com/tiketeer/Tiketeer/domain/member/usecase/dto/SendPwdChangeEmailCommandDto.java
  src/main/java/com/tiketeer/Tiketeer/infra/alarm/email/EmailService.java
  src/main/java/com/tiketeer/Tiketeer/infra/alarm/email/view/AuthenticateEmailViewStrategy.java
  src/main/java/com/tiketeer/Tiketeer/infra/alarm/email/view/EmailViewStrategy.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/controller/MemberControllerTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/usecase/SendPasswordChangeEmailUseCaseTest.java
  src/test/java/com/tiketeer/Tiketeer/infra/alarm/email/EmailServiceTest.java
  src/test/java/com/tiketeer/Tiketeer/testhelper/TestHelper.java
Labels: enhancement

#52 [DEV-123] flyway에 누락되어 있던 refresh_tokens 테이블 DDL 작성
  src/main/java/com/tiketeer/Tiketeer/domain/member/RefreshToken.java
  src/main/resources/db/migration/V1.2__create_table_refresh_token.sql
Labels: enhancement

#55 [DEV-96] TicketingControllerTest 내 누락된 EP에 대한 테스트 추가
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/controller/TicketingController.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/controller/dto/PatchTicketingRequestDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/controller/dto/PostTicketingRequestDto.java
  src/main/java/com/tiketeer/Tiketeer/domain/ticketing/service/TicketingService.java
  src/test/java/com/tiketeer/Tiketeer/domain/member/controller/MemberControllerTest.java
  src/test/java/com/tiketeer/Tiketeer/domain/ticketing/controller/TicketingControllerTest.java
Labels: enhancement
